#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 17.0, \"native_evidence_sha256\": \"26b44adedfea18e204d5d242dc9fbccae1a256621772adc40456eddc444460c7\", \"preserved_priorities\": [\"seller 15 percent discount floor\", \"buyer robust warranty and after-sales priority\", \"buyer timely-delivery priority\"], \"price_usd\": 15.0, \"product\": \"Replacement Remote Control for HISENSE EQK AC Air Conditioner\", \"seller_floor_usd\": 14.433, \"source_task_id\": \"bargaining:001\", \"terms\": {\"after_sales_support\": true, \"compatibility\": \"HISENSE EQK confirmed\", \"delivery_days\": 7, \"warranty_months\": 12}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 17.0, \"native_evidence_sha256\": \"26b44adedfea18e204d5d242dc9fbccae1a256621772adc40456eddc444460c7\", \"preserved_priorities\": [\"seller 15 percent discount floor\", \"buyer robust warranty and after-sales priority\", \"buyer timely-delivery priority\"], \"price_usd\": 15.0, \"product\": \"Replacement Remote Control for HISENSE EQK AC Air Conditioner\", \"seller_floor_usd\": 14.433, \"source_task_id\": \"bargaining:001\", \"terms\": {\"after_sales_support\": true, \"compatibility\": \"HISENSE EQK confirmed\", \"delivery_days\": 7, \"warranty_months\": 12}}, \"product\": \"Replacement Remote Control for HISENSE EQK AC Air Conditioner\", \"source_task_id\": \"bargaining:001\", \"superseded_revisions\": [{\"delivery_days\": 14, \"price\": 16.98, \"revision\": 1, \"status\": \"superseded\", \"warranty_months\": 0}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller 15 percent discount floor\", \"buyer robust warranty and after-sales priority\", \"buyer timely-delivery priority\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
p={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-0e3747a21b','source_task_id':'bargaining:001','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 16.98, "warranty_months": 0, "delivery_days": 14, "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'26b44adedfea18e204d5d242dc9fbccae1a256621772adc40456eddc444460c7'}
p['receipt_sha256']=hashlib.sha256(json.dumps(p,sort_keys=True,separators=(',',':')).encode()).hexdigest(); pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(p,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
