#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 22.0, \"native_evidence_sha256\": \"6cbfa25aae32267135484905bbc784206a3e710839e343e34c4dc809e513cd03\", \"preserved_priorities\": [\"seller profit-margin floor\", \"seller production-demand balance\", \"buyer warranty and after-sales priority\", \"source-stated battery condition explicitly dispositioned\"], \"price_usd\": 21.2, \"product\": \"Girls 2 Piece Matching Outfit For Every Holiday Skirt Sets 1\", \"seller_floor_usd\": 21.1905, \"source_task_id\": \"bargaining:009\", \"terms\": {\"after_sales_support\": true, \"battery_condition\": \"not_applicable_verified\", \"production_schedule\": \"volume-aligned\", \"quality_rating_evidence\": 4.6, \"two_piece_holiday_set\": \"verified\", \"warranty_months\": 12}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 22.0, \"native_evidence_sha256\": \"6cbfa25aae32267135484905bbc784206a3e710839e343e34c4dc809e513cd03\", \"preserved_priorities\": [\"seller profit-margin floor\", \"seller production-demand balance\", \"buyer warranty and after-sales priority\", \"source-stated battery condition explicitly dispositioned\"], \"price_usd\": 21.2, \"product\": \"Girls 2 Piece Matching Outfit For Every Holiday Skirt Sets 1\", \"seller_floor_usd\": 21.1905, \"source_task_id\": \"bargaining:009\", \"terms\": {\"after_sales_support\": true, \"battery_condition\": \"not_applicable_verified\", \"production_schedule\": \"volume-aligned\", \"quality_rating_evidence\": 4.6, \"two_piece_holiday_set\": \"verified\", \"warranty_months\": 12}}, \"product\": \"Girls 2 Piece Matching Outfit For Every Holiday Skirt Sets 1\", \"source_task_id\": \"bargaining:009\", \"superseded_revisions\": [{\"price\": 24.93, \"quality_evidence\": \"missing\", \"revision\": 1, \"status\": \"superseded\", \"warranty_months\": 0}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller profit-margin floor\", \"seller production-demand balance\", \"buyer warranty and after-sales priority\", \"source-stated battery condition explicitly dispositioned\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
v={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-9bcba02feb','source_task_id':'bargaining:009','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 24.93, "warranty_months": 0, "quality_evidence": "missing", "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'6cbfa25aae32267135484905bbc784206a3e710839e343e34c4dc809e513cd03'};v['receipt_sha256']=hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest();pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(v,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
