#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 93.0, \"native_evidence_sha256\": \"dd75f6b18b97c8948884106de2ffd76c979fa0e4c85117561f2a14edb0d34cad\", \"preserved_priorities\": [\"seller long-term-contract priority\", \"seller production-demand balance\", \"buyer price-and-quality priority\", \"source-stated battery condition explicitly dispositioned\"], \"price_usd\": 93.0, \"product\": \"Women's Charlie Boot\", \"seller_floor_usd\": 87.9835, \"source_task_id\": \"bargaining:007\", \"terms\": {\"battery_condition\": \"not_applicable_verified\", \"charlie_boot_quality_inspection\": \"passed\", \"long_term_contract_months\": 12, \"production_schedule\": \"demand-aligned\", \"rating_evidence\": 4.0}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 93.0, \"native_evidence_sha256\": \"dd75f6b18b97c8948884106de2ffd76c979fa0e4c85117561f2a14edb0d34cad\", \"preserved_priorities\": [\"seller long-term-contract priority\", \"seller production-demand balance\", \"buyer price-and-quality priority\", \"source-stated battery condition explicitly dispositioned\"], \"price_usd\": 93.0, \"product\": \"Women's Charlie Boot\", \"seller_floor_usd\": 87.9835, \"source_task_id\": \"bargaining:007\", \"terms\": {\"battery_condition\": \"not_applicable_verified\", \"charlie_boot_quality_inspection\": \"passed\", \"long_term_contract_months\": 12, \"production_schedule\": \"demand-aligned\", \"rating_evidence\": 4.0}}, \"product\": \"Women's Charlie Boot\", \"source_task_id\": \"bargaining:007\", \"superseded_revisions\": [{\"long_term_contract_months\": 0, \"price\": 103.51, \"quality_assurance\": false, \"revision\": 1, \"status\": \"superseded\"}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller long-term-contract priority\", \"seller production-demand balance\", \"buyer price-and-quality priority\", \"source-stated battery condition explicitly dispositioned\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
v={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-c7d591d986','source_task_id':'bargaining:007','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 103.51, "quality_assurance": False, "long_term_contract_months": 0, "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'dd75f6b18b97c8948884106de2ffd76c979fa0e4c85117561f2a14edb0d34cad'};v['receipt_sha256']=hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest();pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(v,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
