#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 49.0, \"native_evidence_sha256\": \"f78636454656be994b93cc08f6ffd1cd61cb775314168b4ccde5e59da6e275f2\", \"preserved_priorities\": [\"seller production and demand priority\", \"buyer price and quality priority\", \"seller long-term contract priority\"], \"price_usd\": 46.75, \"product\": \"Women Western Cowgirl pointed-toe rhinestone ankle booties\", \"seller_floor_usd\": 46.7415, \"source_task_id\": \"bargaining:014\", \"terms\": {\"quality_inspection\": \"rhinestone and pointed-toe inspection passed\", \"rating_evidence\": 4.5, \"replenishment\": \"scalable\", \"supply_commitment_months\": 12}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 49.0, \"native_evidence_sha256\": \"f78636454656be994b93cc08f6ffd1cd61cb775314168b4ccde5e59da6e275f2\", \"preserved_priorities\": [\"seller production and demand priority\", \"buyer price and quality priority\", \"seller long-term contract priority\"], \"price_usd\": 46.75, \"product\": \"Women Western Cowgirl pointed-toe rhinestone ankle booties\", \"seller_floor_usd\": 46.7415, \"source_task_id\": \"bargaining:014\", \"terms\": {\"quality_inspection\": \"rhinestone and pointed-toe inspection passed\", \"rating_evidence\": 4.5, \"replenishment\": \"scalable\", \"supply_commitment_months\": 12}}, \"product\": \"Women Western Cowgirl pointed-toe rhinestone ankle booties\", \"source_task_id\": \"bargaining:014\", \"superseded_revisions\": [{\"price\": 54.99, \"quality_assurance\": false, \"revision\": 1, \"status\": \"superseded\", \"supply_commitment_months\": 0}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller production and demand priority\", \"buyer price and quality priority\", \"seller long-term contract priority\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
p={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-88206c382b','source_task_id':'bargaining:014','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 54.99, "quality_assurance": False, "supply_commitment_months": 0, "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'f78636454656be994b93cc08f6ffd1cd61cb775314168b4ccde5e59da6e275f2'}
p['receipt_sha256']=hashlib.sha256(json.dumps(p,sort_keys=True,separators=(',',':')).encode()).hexdigest(); pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(p,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
