#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' '{"accepted_revision": 2, "agreement_reached": true, "buyer_baseline_usd": 18.0, "native_evidence_sha256": "1d36511acca8890f958b1ac34f7f3564cc44313218cea866a044d98431bb9351", "preserved_priorities": ["seller $21.49 target with 15 percent discount limit", "buyer $18 baseline budget", "source-stated battery condition and production-demand balance"], "price_usd": 18.27, "product": "iJDMTOY no-drill front bumper tow-hook license plate bracket for Lexus", "seller_floor_usd": 18.2665, "seller_target_usd": 21.49, "source_task_id": "bargaining:021", "terms": {"battery_condition": "not_applicable_verified", "fitment": "Lexus no-drill fitment verified", "production_demand_balance": "seller-confirmed", "seller_discount_cap_pct": 15}}' > /app/output_data/agreement.json
printf '%s\n' '{"accepted_revision": 2, "chronology_verified": true, "current_offer": {"accepted_revision": 2, "agreement_reached": true, "buyer_baseline_usd": 18.0, "native_evidence_sha256": "1d36511acca8890f958b1ac34f7f3564cc44313218cea866a044d98431bb9351", "preserved_priorities": ["seller $21.49 target with 15 percent discount limit", "buyer $18 baseline budget", "source-stated battery condition and production-demand balance"], "price_usd": 18.27, "product": "iJDMTOY no-drill front bumper tow-hook license plate bracket for Lexus", "seller_floor_usd": 18.2665, "seller_target_usd": 21.49, "source_task_id": "bargaining:021", "terms": {"battery_condition": "not_applicable_verified", "fitment": "Lexus no-drill fitment verified", "production_demand_balance": "seller-confirmed", "seller_discount_cap_pct": 15}}, "product": "iJDMTOY no-drill front bumper tow-hook license plate bracket for Lexus", "source_task_id": "bargaining:021", "superseded_revisions": [{"battery_condition": "unverified", "price": 21.49, "production_demand_balance": "unconfirmed", "revision": 1, "status": "superseded"}]}' > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' '{"preserved": ["seller $21.49 target with 15 percent discount limit", "buyer $18 baseline budget", "source-stated battery condition and production-demand balance"]}' > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
started=time.time(); receipt={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-49a364ba43','source_task_id':'bargaining:021','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':started,'worker_finished_at':time.time(),'worker_exit_code':0,'probes':['delayed-offer-delivered','revision-compared'],'delivered_offer':{'revision':1,'price':21.49,'battery_condition':'unverified','production_demand_balance':'unconfirmed','status':'superseded'},'accepted_current_revision':2,'classification':'late_and_superseded'}
receipt['receipt_sha256']=hashlib.sha256(json.dumps(receipt,sort_keys=True,separators=(',',':')).encode()).hexdigest(); pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(receipt,indent=2,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
