#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 13.5, \"native_evidence_sha256\": \"03699ff308dc4a973ac99436eed375cc1f6740b9b34d753d61497b64a2688ff4\", \"preserved_priorities\": [\"seller logistics-cost reduction\", \"seller production-demand balance\", \"buyer timely-delivery priority\", \"buyer price-and-quality priority\"], \"price_usd\": 13.5, \"product\": \"Blue Brianna Women's Reading Glasses with Case\", \"seller_floor_usd\": 13.482, \"source_task_id\": \"bargaining:019\", \"terms\": {\"blue_brianna_with_case\": \"verified\", \"consolidated_logistics\": true, \"delivery_days\": 7, \"production_lot\": \"demand-aligned\", \"quality_rating_evidence\": 4.2}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 13.5, \"native_evidence_sha256\": \"03699ff308dc4a973ac99436eed375cc1f6740b9b34d753d61497b64a2688ff4\", \"preserved_priorities\": [\"seller logistics-cost reduction\", \"seller production-demand balance\", \"buyer timely-delivery priority\", \"buyer price-and-quality priority\"], \"price_usd\": 13.5, \"product\": \"Blue Brianna Women's Reading Glasses with Case\", \"seller_floor_usd\": 13.482, \"source_task_id\": \"bargaining:019\", \"terms\": {\"blue_brianna_with_case\": \"verified\", \"consolidated_logistics\": true, \"delivery_days\": 7, \"production_lot\": \"demand-aligned\", \"quality_rating_evidence\": 4.2}}, \"product\": \"Blue Brianna Women's Reading Glasses with Case\", \"source_task_id\": \"bargaining:019\", \"superseded_revisions\": [{\"delivery_days\": 14, \"price\": 14.98, \"quality_evidence\": \"missing\", \"revision\": 1, \"status\": \"superseded\"}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller logistics-cost reduction\", \"seller production-demand balance\", \"buyer timely-delivery priority\", \"buyer price-and-quality priority\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
v={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-c4cd816269','source_task_id':'bargaining:019','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 14.98, "delivery_days": 14, "quality_evidence": "missing", "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'03699ff308dc4a973ac99436eed375cc1f6740b9b34d753d61497b64a2688ff4'};v['receipt_sha256']=hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest();pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(v,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
