#!/bin/bash
set -euo pipefail
cd /testbed
printf '%s' 'ZGlmZiAtLWdpdCBhL3N5bXB5L2dlb21ldHJ5L3BvaW50LnB5IGIvc3ltcHkvZ2VvbWV0cnkvcG9pbnQucHkKLS0tIGEvc3ltcHkvZ2VvbWV0cnkvcG9pbnQucHkKKysrIGIvc3ltcHkvZ2VvbWV0cnkvcG9pbnQucHkKQEAgLTE1Miw3ICsxNTIsNyBAQCBkZWYgX19uZXdfXyhjbHMsICphcmdzLCAqKmt3YXJncyk6CiAgICAgICAgICAgICAgICAgICAgICAgICAnd2Fybicgb3IgJ2lnbm9yZScuJycnKSkKICAgICAgICAgaWYgYW55KGNvb3Jkc1tkaW06XSk6CiAgICAgICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCdOb256ZXJvIGNvb3JkaW5hdGVzIGNhbm5vdCBiZSByZW1vdmVkLicpCi0gICAgICAgIGlmIGFueShhLmlzX251bWJlciBhbmQgaW0oYSkgZm9yIGEgaW4gY29vcmRzKToKKyAgICAgICAgaWYgYW55KGEuaXNfbnVtYmVyIGFuZCBpbShhKS5pc196ZXJvIGlzIEZhbHNlIGZvciBhIGluIGNvb3Jkcyk6CiAgICAgICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCdJbWFnaW5hcnkgY29vcmRpbmF0ZXMgYXJlIG5vdCBwZXJtaXR0ZWQuJykKICAgICAgICAgaWYgbm90IGFsbChpc2luc3RhbmNlKGEsIEV4cHIpIGZvciBhIGluIGNvb3Jkcyk6CiAgICAgICAgICAgICByYWlzZSBUeXBlRXJyb3IoJ0Nvb3JkaW5hdGVzIG11c3QgYmUgdmFsaWQgU3ltUHkgZXhwcmVzc2lvbnMuJykK' | base64 -d > /tmp/equivalent.patch
printf '%s' 'ZGlmZiAtLWdpdCBhL3N5bXB5L2dlb21ldHJ5L3Rlc3RzL3Rlc3RfcG9pbnQucHkgYi9zeW1weS9nZW9tZXRyeS90ZXN0cy90ZXN0X3BvaW50LnB5Ci0tLSBhL3N5bXB5L2dlb21ldHJ5L3Rlc3RzL3Rlc3RfcG9pbnQucHkKKysrIGIvc3ltcHkvZ2VvbWV0cnkvdGVzdHMvdGVzdF9wb2ludC5weQpAQCAtMSw1ICsxLDYgQEAKIGZyb20gc3ltcHkuY29yZS5iYXNpYyBpbXBvcnQgQmFzaWMKIGZyb20gc3ltcHkuY29yZS5udW1iZXJzIGltcG9ydCAoSSwgUmF0aW9uYWwsIHBpKQorZnJvbSBzeW1weS5jb3JlLnBhcmFtZXRlcnMgaW1wb3J0IGV2YWx1YXRlCiBmcm9tIHN5bXB5LmNvcmUuc2luZ2xldG9uIGltcG9ydCBTCiBmcm9tIHN5bXB5LmNvcmUuc3ltYm9sIGltcG9ydCBTeW1ib2wKIGZyb20gc3ltcHkuY29yZS5zeW1waWZ5IGltcG9ydCBzeW1waWZ5CkBAIC00NTIsNiArNDUzLDEyIEBAIGRlZiB0ZXN0X19ub3JtYWxpemVfZGltZW5zaW9uKCk6CiAgICAgICAgIFBvaW50KDEsIDIsIDApLCBQb2ludCgzLCA0LCAwKV0KIAogCitkZWYgdGVzdF9pc3N1ZV8yMjY4NCgpOgorICAgICMgVXNlZCB0byBnaXZlIGFuIGVycm9yCisgICAgd2l0aCBldmFsdWF0ZShGYWxzZSk6CisgICAgICAgIFBvaW50KDEsIDIpCisKKwogZGVmIHRlc3RfZGlyZWN0aW9uX2Nvc2luZSgpOgogICAgIHAxID0gUG9pbnQzRCgwLCAwLCAwKQogICAgIHAyID0gUG9pbnQzRCgxLCAxLCAxKQo=' | base64 -d > /tmp/equivalent-test.patch
patch -p1 < /tmp/equivalent.patch
if [[ -s /tmp/equivalent-test.patch ]]; then patch -p1 < /tmp/equivalent-test.patch; fi

mkdir -p /app/output_data
printf '%s\n' '{"status":"alternative_checkpoint"}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' '{"source_task_id":"sympy__sympy-22714","preserved":true}' > /app/output_data/preserved_source_facts.json
python /app/task_file/scripts/event_worker.py --workspace /testbed
python /app/task_file/scripts/write_manifest.py
