#!/bin/bash
set -euo pipefail
mkdir -p /app/output_data
printf '%s\n' "{\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 42.0, \"native_evidence_sha256\": \"457c9c1577362a9aa162884826eb4f58f1625bc2e70934c6361dbb5aff6085e7\", \"preserved_priorities\": [\"seller premium-value rationale\", \"seller long-term-contract priority\", \"buyer timely-delivery priority\", \"buyer warranty and after-sales priority\"], \"price_usd\": 42.0, \"product\": \"3 Tier Utility Rolling Cart Multifunction Organizer Shelf Storage Cart in Pink\", \"seller_floor_usd\": 37.592, \"source_task_id\": \"bargaining:004\", \"terms\": {\"after_sales_support\": true, \"delivery_days\": 7, \"long_term_replenishment\": true, \"quality_rating_evidence\": 4.7, \"three_tier_pink_cart\": \"verified\", \"warranty_months\": 12}}" > /app/output_data/agreement.json
printf '%s\n' "{\"accepted_revision\": 2, \"chronology_verified\": true, \"current_offer\": {\"accepted_revision\": 2, \"agreement_reached\": true, \"buyer_ceiling_usd\": 42.0, \"native_evidence_sha256\": \"457c9c1577362a9aa162884826eb4f58f1625bc2e70934c6361dbb5aff6085e7\", \"preserved_priorities\": [\"seller premium-value rationale\", \"seller long-term-contract priority\", \"buyer timely-delivery priority\", \"buyer warranty and after-sales priority\"], \"price_usd\": 42.0, \"product\": \"3 Tier Utility Rolling Cart Multifunction Organizer Shelf Storage Cart in Pink\", \"seller_floor_usd\": 37.592, \"source_task_id\": \"bargaining:004\", \"terms\": {\"after_sales_support\": true, \"delivery_days\": 7, \"long_term_replenishment\": true, \"quality_rating_evidence\": 4.7, \"three_tier_pink_cart\": \"verified\", \"warranty_months\": 12}}, \"product\": \"3 Tier Utility Rolling Cart Multifunction Organizer Shelf Storage Cart in Pink\", \"source_task_id\": \"bargaining:004\", \"superseded_revisions\": [{\"delivery_days\": 14, \"price\": 46.99, \"revision\": 1, \"status\": \"superseded\", \"warranty_months\": 0}]}" > /app/output_data/negotiation_ledger.json
printf '%s\n' '{"status":"current_revision_persisted","revision":2}' > /app/output_data/provisional_checkpoint.json
printf '%s\n' "{\"preserved\": [\"seller premium-value rationale\", \"seller long-term-contract priority\", \"buyer timely-delivery priority\", \"buyer warranty and after-sales priority\"]}" > /app/output_data/preserved_source_facts.json
python3 - <<'PY'
import hashlib,json,pathlib,time
v={'schema_version':'async-rbench-event-receipt-v1','case_id':'mab-late-constraint-db9b3a6953','source_task_id':'bargaining:004','event':'late_superseded_offer_delivery','result_kind':'result_02','released_at':3,'worker_started_at':time.time(),'worker_finished_at':time.time(),'worker_exit_code':0,'delivered_offer':{"revision": 1, "price": 46.99, "delivery_days": 14, "warranty_months": 0, "status": "superseded"},'accepted_current_revision':2,'classification':'late_and_superseded','native_evidence_sha256':'457c9c1577362a9aa162884826eb4f58f1625bc2e70934c6361dbb5aff6085e7'};v['receipt_sha256']=hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest();pathlib.Path('/app/output_data/event_receipt.json').write_text(json.dumps(v,sort_keys=True)+'\n')
PY
python3 /app/task_file/scripts/write_manifest.py
